### ISSUE TITLE
ngrok Error: certificate has expired

### ISSUE THREAD

**Issue by matteo-gheri-pocketworks** [gjaldon/heroku-buildpack-phoenix-static#122]
Hello, I'm trying to deploy some changes of my app but I'm getting the following error while building dependencies:

```ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
remote:        ngrok - error downloading binary { Error: certificate has expired
remote:        at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
remote:        at emitNone (events.js:106:13)
remote:        at TLSSocket.emit (events.js:208:7)
remote:        at TLSSocket._finishInit (_tls_wrap.js:639:8)
remote:        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'CERT_HAS_EXPIRED' }
```

I've tried with curl and the certificate seems valid

```curl -XGET -vvv https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 54.161.241.46...
* TCP_NODELAY set
* Connected to bin.equinox.io (54.161.241.46) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=bin.equinox.io
*  start date: Jan 13 23:02:06 2022 GMT
*  expire date: Apr 13 23:02:05 2022 GMT
*  subjectAltName: host "bin.equinox.io" matched cert's "bin.equinox.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
```

I've also tried to run the curl command on Heroku and still getting a valid ssl exchange.

**Comment by gjaldon** [comment]
@matteo-gheri-pocketworks thank you for closing the issue. What caused the issue though? Might be good to document it here in case someone else encounters it in the future.

**Comment by matteo-gheri-pocketworks** [comment]
I think might have just been some cache issue, if I remember correctly i just purged the heroku build cache.

**Comment by gjaldon** [comment]
Ahhh, I guess it's always good to try and purge the cache. Thanks @matteo-gheri-pocketworks! 🙏🏼
